In [ ]:
# criar o navegador
from selenium import webdriver
from selenium.webdriver.common.by import By


navegador = webdriver.Chrome()

In [15]:
# abrir a página index (entrar no site da busca jurídica)
import os

caminho = os.getcwd()
arquivo = caminho + r"\index.html"
navegador.get(arquivo)

In [ ]:
from selenium.webdriver import ActionChains
def escolher_cidade(cidade_escolhida):
    menu = navegador.find_element(By.TAG_NAME, 'button')
    ActionChains(navegador).move_to_element(menu).perform()
    cidades = navegador.find_elements(By.TAG_NAME, 'a')
    for cidade in cidades:
        if cidade.text == cidade_escolhida:
            cidade.click()

In [ ]:
import time
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

def verificar_status(linha):
    nova_aba = navegador.window_handles[1]
    navegador.switch_to.window(nova_aba)
    navegador.find_element(By.NAME, 'nome').send_keys(linha.Nome)
    navegador.find_element(By.NAME, 'advogado').send_keys(linha.Advogado)
    navegador.find_element(By.NAME, 'numero').send_keys(linha.Processo)
    navegador.find_element(By.CLASS_NAME, 'registerbtn').click()
    time.sleep(0.5)
    element = WebDriverWait(navegador, 2).until(EC.alert_is_present())
    element.accept()
    time.sleep(2)
    element2 = WebDriverWait(navegador, 2).until(EC.alert_is_present())
    status = element2.text
    element2.accept()
    navegador.close()
    navegador.switch_to.window(navegador.window_handles[0])
    return status

In [ ]:
# importar a base de dados
import pandas as pd

tabela = pd.read_excel("Processos.xlsx")
tabela["Status"] = tabela["Status"].astype('str')
display(tabela)

for indice, linha in tabela.iterrows():
    escolher_cidade(linha.Cidade)
    status = verificar_status(linha)
    tabela.loc[tabela["Processo"] == linha.Processo, 'Status'] = status
    time.sleep(1)
display(tabela)

tabela.to_excel("Processos realizado.xlsx")

     Nome      Advogado Processo            Cidade Status
0    Lira   Alon Lawyer   PC6592  Distrito Federal    NaN
1    João   Lawyer Alon   EB3792    Rio de Janeiro    NaN
2  Amanda  Amanda mesmo   MM1043    Rio de Janeiro    NaN
3   Carol        Amanda   PC5197         São Paulo    NaN

,Nome,Advogado,Processo,Cidade,Status
0,Lira,Alon Lawyer,PC6592,Distrito Federal,Processo encontrado com sucesso! Deseja acessar?
1,João,Lawyer Alon,EB3792,Rio de Janeiro,Processo encontrado com sucesso! Deseja acessar?
2,Amanda,Amanda mesmo,MM1043,Rio de Janeiro,Processo encontrado com sucesso! Deseja acessar?
3,Carol,Amanda,PC5197,São Paulo,Nenhum processo encontrado!