#### Alpha Vantage

https://www.alphavantage.co/documentation/

##### Pegando cotações semanais - JSON

In [8]:
import requests
from chave import chave_api
from pprint import pprint

url = f'https://www.alphavantage.co/query?function=TIME_SERIES_WEEKLY_ADJUSTED&symbol=ITUB3.SAO&apikey={chave_api}'

r = requests.get(url)
dic_requisicao = r.json()
print(dic_requisicao)

{'Meta Data': {'1. Information': 'Weekly Adjusted Prices and Volumes', '2. Symbol': 'ITUB3.SAO', '3. Last Refreshed': '2026-08-03', '4. Time Zone': 'US/Eastern'}, 'Weekly Adjusted Time Series': {'2026-08-03': {'1. open': '45.7000', '2. high': '46.0300', '3. low': '45.3100', '4. close': '45.6300', '5. adjusted close': '45.6300', '6. volume': '1201100', '7. dividend amount': '0.0000'}, '2026-07-31': {'1. open': '44.8100', '2. high': '46.2000', '3. low': '44.2600', '4. close': '45.3400', '5. adjusted close': '45.3400', '6. volume': '9578800', '7. dividend amount': '0.0182'}, '2026-07-24': {'1. open': '44.7800', '2. high': '45.7600', '3. low': '44.6000', '4. close': '44.7000', '5. adjusted close': '44.6821', '6. volume': '7667000', '7. dividend amount': '0.0000'}, '2026-07-17': {'1. open': '46.4600', '2. high': '46.8400', '3. low': '44.6500', '4. close': '44.7800', '5. adjusted close': '44.7620', '6. volume': '10470500', '7. dividend amount': '0.0000'}, '2026-07-10': {'1. open': '44.4800', '2. high': '46.8000', '3. low': '44.0100', '4. close': '46.4600', '5. adjusted close': '46.4414', '6. volume': '8955800', '7. dividend amount': '0.0000'}, '2026-07-03': {'1. open': '44.2600', '2. high': '45.2300', '3. low': '43.6600', '4. close': '44.5000', '5. adjusted close': '44.4822', '6. volume': '6854100', '7. dividend amount': '0.0182'}, '2026-06-26': {'1. open': '42.1000', '2. high': '44.8500', '3. low': '42.0400', '4. close': '44.3800', '5. adjusted close': '44.3440', '6. volume': '11995200', '7. dividend amount': '0.0000'}, '2026-06-19': {'1. open': '42.3100', '2. high': '43.3700', '3. low': '41.5000', '4. close': '41.9300', '5. adjusted close': '41.8960', '6. volume': '13231700', '7. dividend amount': '0.3619'}, '2026-06-12': {'1. open': '40.4700', '2. high': '43.0500', '3. low': '40.1800', '4. close': '41.8800', '5. adjusted close': '41.4938', '6. volume': '21084600', '7. dividend amount': '0.0000'}, '2026-06-05': {'1. open': '40.2800', '2. high': '40.9500', '3. low': '39.6100', '4. close': '40.4600', '5. adjusted close': '40.0869', '6. volume': '19572200', '7. dividend amount': '0.0000'}, '2026-05-29': {'1. open': '40.3400', '2. high': '41.5000', '3. low': '39.8800', '4. close': '40.0600', '5. adjusted close': '39.6906', '6. volume': '95298700', '7. dividend amount': '0.0182'}, '2026-05-22': {'1. open': '40.1600', '2. high': '41.0100', '3. low': '39.2500', '4. close': '40.2600', '5. adjusted close': '39.8707', '6. volume': '9577900', '7. dividend amount': '0.0000'}, '2026-05-15': {'1. open': '41.0500', '2. high': '41.1500', '3. low': '39.7400', '4. close': '40.2600', '5. adjusted close': '39.8707', '6. volume': '14638900', '7. dividend amount': '0.0000'}, '2026-05-08': {'1. open': '43.2400', '2. high': '43.4200', '3. low': '40.5700', '4. close': '41.3900', '5. adjusted close': '40.9898', '6. volume': '10568000', '7. dividend amount': '0.0000'}, '2026-04-30': {'1. open': '44.3100', '2. high': '44.5000', '3. low': '42.2000', '4. close': '43.5500', '5. adjusted close': '43.1289', '6. volume': '10866700', '7. dividend amount': '0.0182'}, '2026-04-24': {'1. open': '46.8300', '2. high': '46.9700', '3. low': '43.7400', '4. close': '44.3200', '5. adjusted close': '43.8728', '6. volume': '5188700', '7. dividend amount': '0.0000'}, '2026-04-17': {'1. open': '45.7000', '2. high': '47.8000', '3. low': '45.2000', '4. close': '46.8300', '5. adjusted close': '46.3575', '6. volume': '7029800', '7. dividend amount': '0.0000'}, '2026-04-10': {'1. open': '42.8100', '2. high': '46.2700', '3. low': '42.2500', '4. close': '45.9300', '5. adjusted close': '45.4665', '6. volume': '6980200', '7. dividend amount': '0.0000'}, '2026-04-02': {'1. open': '41.1400', '2. high': '43.7400', '3. low': '40.7600', '4. close': '42.6500', '5. adjusted close': '42.2196', '6. volume': '10227200', '7. dividend amount': '0.0182'}, '2026-03-27': {'1. open': '41.0900', '2. high': '42.3500', '3. low': '40.3800', '4. close': '40.7100', '5. adjusted close': '40.2814', '6. volume': '11441200', '7. dividend amount': '0.0000'}, '2026-03-20': {'1. open': '41.7000', '2. high': '42.1500', '3. low': '40.2300', '4. close': '40.4900', '5. adjusted close': '40.0638', '6. volume': '11379100', '7. dividend amount': '0.0000'}, '2026-03-13': {'1. open': '40.4400', '2. high': '42.3200', '3. low': '40.2300', '4. close': '41.0300', '5. adjusted close': '40.5981', '6. volume': '6381500', '7. dividend amount': '0.0000'}, '2026-03-06': {'1. open': '42.7800', '2. high': '43.3900', '3. low': '40.4200', '4. close': '40.8100', '5. adjusted close': '40.3804', '6. volume': '6541100', '7. dividend amount': '0.0000'}, '2026-02-27': {'1. open': '45.8700', '2. high': '45.8700', '3. low': '43.4000', '4. close': '43.5800', '5. adjusted close': '43.1212', '6. volume': '8154200', '7. dividend amount': '0.0242'}, '2026-02-20': {'1. open': '44.3500', '2. high': '46.1200', '3. low': '44.3000', '4. close': '46.0600', '5. adjusted close': '45.5503', '6. volume': '3191900', '7. dividend amount': '0.0000'}, '2026-02-13': {'1. open': '43.5100', '2. high': '45.9500', '3. low': '43.2800', '4. close': '44.3400', '5. adjusted close': '43.8494', '6. volume': '5620600', '7. dividend amount': '0.0000'}, '2026-02-06': {'1. open': '42.0500', '2. high': '43.7400', '3. low': '41.1300', '4. close': '43.4400', '5. adjusted close': '42.9593', '6. volume': '4771900', '7. dividend amount': '0.0000'}, '2026-01-30': {'1. open': '40.7000', '2. high': '43.6300', '3. low': '40.2000', '4. close': '41.9400', '5. adjusted close': '41.4759', '6. volume': '6023800', '7. dividend amount': '0.0182'}, '2026-01-23': {'1. open': '37.0000', '2. high': '41.0000', '3. low': '36.1900', '4. close': '40.7300', '5. adjusted close': '40.2623', '6. volume': '6871700', '7. dividend amount': '0.0000'}, '2026-01-16': {'1. open': '37.0900', '2. high': '37.2400', '3. low': '36.3100', '4. close': '36.9500', '5. adjusted close': '36.5257', '6. volume': '4093300', '7. dividend amount': '0.0000'}, '2026-01-09': {'1. open': '36.3500', '2. high': '37.7700', '3. low': '36.2800', '4. close': '37.0500', '5. adjusted close': '36.6245', '6. volume': '5628400', '7. dividend amount': '0.0000'}, '2026-01-02': {'1. open': '36.6500', '2. high': '36.8000', '3. low': '36.3100', '4. close': '36.3100', '5. adjusted close': '35.8930', '6. volume': '1144700', '7. dividend amount': '0.0000'}, '2025-12-30': {'1. open': '36.0500', '2. high': '36.7100', '3. low': '35.8100', '4. close': '36.3500', '5. adjusted close': '35.9326', '6. volume': '1246300', '7. dividend amount': '0.0182'}, '2025-12-26': {'1. open': '35.8500', '2. high': '36.0900', '3. low': '35.7000', '4. close': '36.0500', '5. adjusted close': '35.6180', '6. volume': '554500', '7. dividend amount': '0.0000'}, '2025-12-23': {'1. open': '36.5600', '2. high': '36.9600', '3. low': '36.3500', '4. close': '36.8500', '5. adjusted close': '35.3480', '6. volume': '2829925', '7. dividend amount': '0.0000'}, '2025-12-19': {'1. open': '36.6600', '2. high': '37.0800', '3. low': '35.3600', '4. close': '36.5600', '5. adjusted close': '35.0698', '6. volume': '8022464', '7. dividend amount': '0.0000'}, '2025-12-12': {'1. open': '38.7200', '2. high': '38.7200', '3. low': '35.4500', '4. close': '36.3400', '5. adjusted close': '34.8588', '6. volume': '6252821', '7. dividend amount': '2.2380'}, '2025-12-05': {'1. open': '38.2200', '2. high': '39.9200', '3. low': '37.8300', '4. close': '38.0200', '5. adjusted close': '34.2690', '6. volume': '7799984', '7. dividend amount': '0.0000'}, '2025-11-28': {'1. open': '35.2600', '2. high': '38.7000', '3. low': '35.2000', '4. close': '38.1800', '5. adjusted close': '34.4132', '6. volume': '7369032', '7. dividend amount': '0.0176'}, '2025-11-21': {'1. open': '35.9800', '2. high': '35.9800', '3. low': '35.0100', '4. close': '35.2600', '5. adjusted close': '31.7656', '6. volume': '2825702', '7. dividend amount': '0.0000'}, '2025-11-14': {'1. open': '35.7500', '2. high': '36.6900', '3. low': '35.5300', '4. close': '35.9200', '5. adjusted close': '32.3602', '6. volume': '3315879', '7. dividend amount': '0.0000'}, '2025-11-07': {'1. open': '35.4100', '2. high': '36.2300', '3. low': '34.7700', '4. close': '35.7500', '5. adjusted close': '32.2070', '6. volume': '2994210', '7. dividend amount': '0.0000'}, '2025-10-31': {'1. open': '34.2000', '2. high': '35.3700', '3. low': '34.0200', '4. close': '35.1400', '5. adjusted close': '31.6575', '6. volume': '2101818', '7. dividend amount': '0.0176'}, '2025-10-24': {'1. open': '33.3100', '2. high': '34.3500', '3. low': '33.2500', '4. close': '33.9700', '5. adjusted close': '30.5876', '6. volume': '2285261', '7. dividend amount': '0.0000'}, '2025-10-17': {'1. open': '33.1000', '2. high': '33.7700', '3. low': '32.5000', '4. close': '33.3100', '5. adjusted close': '29.9933', '6. volume': '2562846', '7. dividend amount': '0.0000'}, '2025-10-10': {'1. open': '33.8800', '2. high': '33.9600', '3. low': '32.8300', '4. close': '33.0700', '5. adjusted close': '29.7772', '6. volume': '2694171', '7. dividend amount': '0.0000'}, '2025-10-03': {'1. open': '34.5400', '2. high': '34.9900', '3. low': '33.4500', '4. close': '33.8800', '5. adjusted close': '30.5065', '6. volume': '4033068', '7. dividend amount': '0.0176'}, '2025-09-26': {'1. open': '34.5500', '2. high': '34.7900', '3. low': '33.9200', '4. close': '34.2700', '5. adjusted close': '30.8414', '6. volume': '2891519', '7. dividend amount': '0.0000'}, '2025-09-19': {'1. open': '33.5800', '2. high': '34.5800', '3. low': '32.8500', '4. close': '34.5500', '5. adjusted close': '31.0934', '6. volume': '3450809', '7. dividend amount': '0.0000'}, '2025-09-12': {'1. open': '34.3400', '2. high': '34.4500', '3. low': '33.2700', '4. close': '33.5600', '5. adjusted close': '30.2024', '6. volume': '2521337', '7. dividend amount': '0.0000'}, '2025-09-05': {'1. open': '34.3500', '2. high': '34.8000', '3. low': '33.6000', '4. close': '34.4500', '5. adjusted close': '31.0034', '6. volume': '2395368', '7. dividend amount': '0.0000'}, '2025-08-29': {'1. open': '33.4100', '2. high': '34.4200', '3. low': '32.5601', '4. close': '34.4100', '5. adjusted close': '30.9674', '6. volume': '3914618', '7. dividend amount': '0.0176'}, '2025-08-22': {'1. open': '33.5000', '2. high': '33.8600', '3. low': '32.1000', '4. close': '33.3500', '5. adjusted close': '29.9974', '6. volume': '3533312', '7. dividend amount': '0.3634'}, '2025-08-15': {'1. open': '32.9500', '2. high': '34.2800', '3. low': '32.8600', '4. close': '33.5000', '5. adjusted close': '29.7957', '6. volume': '2696025', '7. dividend amount': '0.0000'}, '2025-08-08': {'1. open': '31.5600', '2. high': '33.0800', '3. low': '31.2400', '4. close': '33.0500', '5. adjusted close': '29.3954', '6. volume': '3375928', '7. dividend amount': '0.0000'}, '2025-08-01': {'1. open': '31.4500', '2. high': '31.7100', '3. low': '30.5001', '4. close': '31.1900', '5. adjusted close': '27.7411', '6. volume': '2794287', '7. dividend amount': '0.0176'}, '2025-07-25': {'1. open': '31.3600', '2. high': '31.9500', '3. low': '31.1900', '4. close': '31.4600', '5. adjusted close': '27.9650', '6. volume': '2480240', '7. dividend amount': '0.0000'}, '2025-07-18': {'1. open': '31.5000', '2. high': '32.2000', '3. low': '31.1300', '4. close': '31.3600', '5. adjusted close': '27.8761', '6. volume': '2662653', '7. dividend amount': '0.0000'}, '2025-07-11': {'1. open': '33.5300', '2. high': '33.6800', '3. low': '31.3400', '4. close': '31.6000', '5. adjusted close': '28.0894', '6. volume': '2488892', '7. dividend amount': '0.0000'}, '2025-07-04': {'1. open': '32.2600', '2. high': '33.8100', '3. low': '32.1000', '4. close': '33.6800', '5. adjusted close': '29.9383', '6. volume': '2550383', '7. dividend amount': '0.0176'}, '2025-06-27': {'1. open': '32.4900', '2. high': '33.0700', '3. low': '31.9400', '4. close': '32.2600', '5. adjusted close': '28.6599', '6. volume': '2121285', '7. dividend amount': '0.0000'}, '2025-06-20': {'1. open': '32.5601', '2. high': '33.0000', '3. low': '32.1200', '4. close': '32.4900', '5. adjusted close': '28.8643', '6. volume': '2414320', '7. dividend amount': '0.0000'}, '2025-06-13': {'1. open': '32.3000', '2. high': '32.5100', '3. low': '31.6400', '4. close': '32.2300', '5. adjusted close': '28.6333', '6. volume': '2901304', '7. dividend amount': '0.3341'}, '2025-06-06': {'1. open': '33.4800', '2. high': '33.5000', '3. low': '32.2100', '4. close': '32.5100', '5. adjusted close': '28.5763', '6. volume': '2374459', '7. dividend amount': '0.0000'}, '2025-05-30': {'1. open': '33.3900', '2. high': '34.1500', '3. low': '32.9400', '4. close': '33.3700', '5. adjusted close': '29.3323', '6. volume': '2604046', '7. dividend amount': '0.0176'}, '2025-05-23': {'1. open': '33.6600', '2. high': '34.3400', '3. low': '32.3600', '4. close': '33.3000', '5. adjusted close': '29.2547', '6. volume': '2876584', '7. dividend amount': '0.0000'}, '2025-05-16': {'1. open': '32.7500', '2. high': '33.7700', '3. low': '32.0500', '4. close': '33.6200', '5. adjusted close': '29.5359', '6. volume': '4046561', '7. dividend amount': '0.0000'}, '2025-05-09': {'1. open': '31.1500', '2. high': '32.8400', '3. low': '30.4900', '4. close': '32.7901', '5. adjusted close': '28.8067', '6. volume': '4416846', '7. dividend amount': '0.0000'}, '2025-05-02': {'1. open': '30.2900', '2. high': '31.4000', '3. low': '30.1400', '4. close': '31.4000', '5. adjusted close': '27.5855', '6. volume': '4791766', '7. dividend amount': '0.0176'}, '2025-04-25': {'1. open': '28.7200', '2. high': '31.1200', '3. low': '28.5400', '4. close': '30.2600', '5. adjusted close': '26.5683', '6. volume': '2436053', '7. dividend amount': '0.0000'}, '2025-04-17': {'1. open': '28.4500', '2. high': '28.8100', '3. low': '28.2500', '4. close': '28.6701', '5. adjusted close': '25.1724', '6. volume': '1414808', '7. dividend amount': '0.0000'}, '2025-04-11': {'1. open': '27.4000', '2. high': '28.4600', '3. low': '27.0200', '4. close': '28.1500', '5. adjusted close': '24.7158', '6. volume': '2768125', '7. dividend amount': '0.0000'}, '2025-04-04': {'1. open': '28.0600', '2. high': '28.5400', '3. low': '27.4800', '4. close': '27.6100', '5. adjusted close': '24.2416', '6. volume': '3333080', '7. dividend amount': '0.0176'}, '2025-03-28': {'1. open': '28.4600', '2. high': '28.9400', '3. low': '27.9100', '4. close': '28.0900', '5. adjusted close': '24.6471', '6. volume': '2461494', '7. dividend amount': '0.0000'}, '2025-03-21': {'1. open': '30.5100', '2. high': '31.2099', '3. low': '28.2400', '4. close': '28.4300', '5. adjusted close': '24.9454', '6. volume': '3979971', '7. dividend amount': '0.0000'}, '2025-03-14': {'1. open': '29.2000', '2. high': '30.5400', '3. low': '28.9099', '4. close': '30.4600', '5. adjusted close': '24.2970', '6. volume': '4258378', '7. dividend amount': '0.0000'}, '2025-03-07': {'1. open': '28.9700', '2. high': '29.4899', '3. low': '28.6100', '4. close': '29.2000', '5. adjusted close': '23.2919', '6. volume': '2245945', '7. dividend amount': '0.0000'}, '2025-02-28': {'1. open': '29.1000', '2. high': '29.3401', '3. low': '28.5001', '4. close': '28.5599', '5. adjusted close': '22.7814', '6. volume': '6108001', '7. dividend amount': '0.0176'}, '2025-02-21': {'1. open': '31.0000', '2. high': '31.7000', '3. low': '28.9400', '4. close': '29.1000', '5. adjusted close': '23.1961', '6. volume': '4579243', '7. dividend amount': '1.5844'}, '2025-02-14': {'1. open': '30.1000', '2. high': '31.1401', '3. low': '29.9700', '4. close': '31.0200', '5. adjusted close': '23.2957', '6. volume': '7406079', '7. dividend amount': '0.0000'}, '2025-02-07': {'1. open': '29.7400', '2. high': '30.4800', '3. low': '29.2301', '4. close': '30.0000', '5. adjusted close': '22.5297', '6. volume': '5073119', '7. dividend amount': '0.0000'}, '2025-01-31': {'1. open': '28.4800', '2. high': '30.1300', '3. low': '28.4000', '4. close': '29.8101', '5. adjusted close': '22.3870', '6. volume': '2304066', '7. dividend amount': '0.0176'}, '2025-01-24': {'1. open': '28.3201', '2. high': '28.7301', '3. low': '28.1800', '4. close': '28.4800', '5. adjusted close': '21.3738', '6. volume': '2646799', '7. dividend amount': '0.0000'}, '2025-01-17': {'1. open': '27.1300', '2. high': '28.5100', '3. low': '27.0501', '4. close': '28.3201', '5. adjusted close': '21.2538', '6. volume': '2279707', '7. dividend amount': '0.0000'}, '2025-01-10': {'1. open': '26.7700', '2. high': '28.0801', '3. low': '26.5100', '4. close': '27.1201', '5. adjusted close': '20.3532', '6. volume': '2567603', '7. dividend amount': '0.0000'}, '2025-01-03': {'1. open': '27.0699', '2. high': '27.1000', '3. low': '26.3400', '4. close': '26.3899', '5. adjusted close': '19.8053', '6. volume': '1784700', '7. dividend amount': '0.0000'}, '2024-12-30': {'1. open': '26.9599', '2. high': '27.1799', '3. low': '26.9000', '4. close': '26.9000', '5. adjusted close': '20.1881', '6. volume': '463736', '7. dividend amount': '0.0176'}, '2024-12-27': {'1. open': '27.1000', '2. high': '27.3800', '3. low': '26.9500', '4. close': '26.9500', '5. adjusted close': '20.2106', '6. volume': '708804', '7. dividend amount': '0.0000'}, '2024-12-23': {'1. open': '27.4001', '2. high': '27.4199', '3. low': '26.9700', '4. close': '27.0601', '5. adjusted close': '20.2931', '6. volume': '564347', '7. dividend amount': '0.0000'}, '2024-12-20': {'1. open': '28.2101', '2. high': '28.2300', '3. low': '26.9100', '4. close': '27.5399', '5. adjusted close': '20.6530', '6. volume': '5272414', '7. dividend amount': '0.0000'}, '2024-12-13': {'1. open': '28.7701', '2. high': '29.6400', '3. low': '28.1900', '4. close': '28.2101', '5. adjusted close': '21.1555', '6. volume': '2976728', '7. dividend amount': '0.3106'}, '2024-12-06': {'1. open': '28.3800', '2. high': '29.2800', '3. low': '28.0500', '4. close': '28.9099', '5. adjusted close': '21.4165', '6. volume': '4913254', '7. dividend amount': '0.0000'}, '2024-11-29': {'1. open': '29.5000', '2. high': '30.3500', '3. low': '28.0500', '4. close': '28.5200', '5. adjusted close': '21.1277', '6. volume': '3042670', '7. dividend amount': '0.0176'}, '2024-11-22': {'1. open': '29.8801', '2. high': '30.0100', '3. low': '29.3501', '4. close': '29.5000', '5. adjusted close': '21.8387', '6. volume': '2371142', '7. dividend amount': '0.0000'}, '2024-11-14': {'1. open': '30.4300', '2. high': '30.6299', '3. low': '29.8200', '4. close': '29.8801', '5. adjusted close': '22.1200', '6. volume': '2173772', '7. dividend amount': '0.0000'}, '2024-11-08': {'1. open': '30.3000', '2. high': '31.6300', '3. low': '30.0700', '4. close': '30.4300', '5. adjusted close': '22.5272', '6. volume': '2835897', '7. dividend amount': '0.0000'}, '2024-11-01': {'1. open': '30.6500', '2. high': '31.0400', '3. low': '30.0200', '4. close': '30.0301', '5. adjusted close': '22.2311', '6. volume': '2182609', '7. dividend amount': '0.0176'}, '2024-10-25': {'1. open': '30.4901', '2. high': '30.9300', '3. low': '30.0100', '4. close': '30.5100', '5. adjusted close': '22.5715', '6. volume': '2964946', '7. dividend amount': '0.0000'}, '2024-10-18': {'1. open': '30.1699', '2. high': '30.7400', '3. low': '29.9900', '4. close': '30.4901', '5. adjusted close': '22.5568', '6. volume': '2882578', '7. dividend amount': '0.0000'}, '2024-10-11': {'1. open': '30.6399', '2. high': '30.8800', '3. low': '30.1600', '4. close': '30.1699', '5. adjusted close': '22.3200', '6. volume': '1717965', '7. dividend amount': '0.0000'}, '2024-10-04': {'1. open': '31.8800', '2. high': '32.0300', '3. low': '30.2701', '4. close': '30.4600', '5. adjusted close': '22.5346', '6. volume': '2214673', '7. dividend amount': '0.0176'}, '2024-09-27': {'1. open': '31.1700', '2. high': '31.9400', '3. low': '30.8800', '4. close': '31.9100', '5. adjusted close': '23.5925', '6. volume': '3225761', '7. dividend amount': '0.0000'}, '2024-09-20': {'1. open': '32.3400', '2. high': '32.5500', '3. low': '31.1300', '4. close': '31.2601', '5. adjusted close': '23.1119', '6. volume': '3827837', '7. dividend amount': '0.2730'}, '2024-09-13': {'1. op

##### Pegando cotações semanais - CSV

In [10]:
import pandas as pd
from io import StringIO

url = f'https://www.alphavantage.co/query?function=TIME_SERIES_WEEKLY_ADJUSTED&symbol=ITUB3.SAO&apikey={chave_api}&datatype=csv'

r = requests.get(url)

tabela = pd.read_csv(StringIO(r.text))
display(tabela)

,timestamp,open,high,low,close,adjusted close,volume,dividend amount
0,2026-08-03,45.7000,46.0300,45.3100,45.6300,45.6300,1201100,0.0000
1,2026-07-31,44.8100,46.2000,44.2600,45.3400,45.3400,9578800,0.0182
2,2026-07-24,44.7800,45.7600,44.6000,44.7000,44.6821,7667000,0.0000
3,2026-07-17,46.4600,46.8400,44.6500,44.7800,44.7620,10470500,0.0000
4,2026-07-10,44.4800,46.8000,44.0100,46.4600,46.4414,8955800,0.0000
...,...,...,...,...,...,...,...,...
1133,2005-02-11,339.9979,350.0020,339.9979,350.0020,1.3278,13685,0.0000
1134,2005-02-04,333.9970,339.9979,330.0008,339.9979,1.2898,246334,0.0000
1135,2005-01-28,344.9998,344.9998,333.9970,333.9970,1.2670,260019,0.0000
1136,2005-01-21,344.0012,344.9998,339.9979,339.9979,1.2898,95795,0.0000
1137,2005-01-14,350.0020,350.0020,344.0012,344.0012,1.3050,1409586,0.0000

#### Cotações

In [14]:
acoes = ['ITUB4', 'ABEV3', 'BBAS3']

compilada = pd.DataFrame()

for acao in acoes:
    url = f'https://www.alphavantage.co/query?function=GLOBAL_QUOTE&symbol={acao}.SAO&apikey={chave_api}&datatype=csv'
    r = requests.get(url)
    tabela = pd.read_csv(StringIO(r.text))
    lista_tabelas = [compilada, tabela]
    compilada = pd.concat(lista_tabelas)

display(compilada)

,symbol,open,high,low,price,volume,latestDay,previousClose,change,changePercent,{
0,ITUB4.SAO,43.35,43.47,42.83,43.17,17021900.0,2026-08-03,42.89,0.28,0.6528%,NaN
"( ""Information"": ""Thank you for using Alpha Vantage! Please consider spreading out your free API requests more sparingly (1 request per second). You may subscribe to any of the premium plans at https://www.alphavantage.co/premium/ to lift the free key rate limit (25 requests per day), raise the per-second burst limit)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"and instantly unlock all premium endpoints"""
"(}, nan)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"( ""Information"": ""Thank you for using Alpha Vantage! Please consider spreading out your free API requests more sparingly (1 request per second). You may subscribe to any of the premium plans at https://www.alphavantage.co/premium/ to lift the free key rate limit (25 requests per day), raise the per-second burst limit)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"and instantly unlock all premium endpoints"""
"(}, nan)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Encontrar ativos

In [16]:
url = f'https://www.alphavantage.co/query?function=SYMBOL_SEARCH&keywords=amazon&apikey={chave_api}&datatype=csv'

r = requests.get(url)

tabela = pd.read_csv(StringIO(r.text))
display(tabela)

,symbol,name,type,region,marketOpen,marketClose,timezone,currency,matchScore
0,AMZN,Amazon.com Inc,Equity,United States,09:30,16:00,UTC-04,USD,0.8000
1,AMZN.TRT,Amazon.com CDR (CAD Hedged),Equity,Toronto,09:30,16:00,UTC-05,CAD,0.6154
2,AMZ.DEX,Amazon.com Inc,Equity,XETRA,08:00,20:00,UTC+02,EUR,0.6000
3,AMZ.FRK,Amazon.com Inc,Equity,Frankfurt,08:00,20:00,UTC+02,EUR,0.6000
4,AMZO34.SAO,Amazon.com Inc,Equity,Brazil/Sao Paolo,10:00,17:30,UTC-03,BRL,0.6000
5,0R1O.LON,Amazon.com Inc.,Equity,United Kingdom,08:00,16:30,UTC+01,USD,0.5714
6,AMZ1.FRK,AMAZON.COM INC.CDR DL-01,Equity,Frankfurt,08:00,20:00,UTC+02,EUR,0.5000
7,AZFL,Amazonas Florestal Ltd,Equity,United States,09:30,16:00,UTC-04,USD,0.4286

### Informações de Resultado

In [19]:
url = f'https://www.alphavantage.co/query?function=EARNINGS&symbol=AMZN&apikey={chave_api}'
r = requests.get(url)
dic_requisicao = r.json()

print(dic_requisicao)

{'symbol': 'AMZN', 'annualEarnings': [{'fiscalDateEnding': '2026-06-30', 'reportedEPS': '4.66'}, {'fiscalDateEnding': '2025-12-31', 'reportedEPS': '7.17'}, {'fiscalDateEnding': '2024-12-31', 'reportedEPS': '5.53'}, {'fiscalDateEnding': '2023-12-31', 'reportedEPS': '2.9'}, {'fiscalDateEnding': '2022-12-31', 'reportedEPS': '-0.27'}, {'fiscalDateEnding': '2021-12-31', 'reportedEPS': '3.25'}, {'fiscalDateEnding': '2020-12-31', 'reportedEPS': '2.09'}, {'fiscalDateEnding': '2019-12-31', 'reportedEPS': '1.14'}, {'fiscalDateEnding': '2018-12-31', 'reportedEPS': '1'}, {'fiscalDateEnding': '2017-12-31', 'reportedEPS': '0.23'}, {'fiscalDateEnding': '2016-12-31', 'reportedEPS': '0.25'}, {'fiscalDateEnding': '2015-12-31', 'reportedEPS': '0.06'}, {'fiscalDateEnding': '2014-12-31', 'reportedEPS': '-0.03'}, {'fiscalDateEnding': '2013-12-31', 'reportedEPS': '-0.07'}, {'fiscalDateEnding': '2012-12-31', 'reportedEPS': '0'}, {'fiscalDateEnding': '2011-12-31', 'reportedEPS': '0.07'}, {'fiscalDateEnding': '2010-12-31', 'reportedEPS': '0.13'}, {'fiscalDateEnding': '2009-12-31', 'reportedEPS': '0.1'}, {'fiscalDateEnding': '2008-12-31', 'reportedEPS': '0.08'}, {'fiscalDateEnding': '2007-12-31', 'reportedEPS': '0.05'}, {'fiscalDateEnding': '2006-12-31', 'reportedEPS': '0.12'}, {'fiscalDateEnding': '2005-12-31', 'reportedEPS': '0.04'}, {'fiscalDateEnding': '2004-12-31', 'reportedEPS': '0.05'}, {'fiscalDateEnding': '2003-12-31', 'reportedEPS': '0.04'}, {'fiscalDateEnding': '2002-12-31', 'reportedEPS': '-0.1024'}, {'fiscalDateEnding': '2001-12-31', 'reportedEPS': '0.06'}, {'fiscalDateEnding': '2000-12-31', 'reportedEPS': '-0.06'}, {'fiscalDateEnding': '1999-12-31', 'reportedEPS': '-0.06'}, {'fiscalDateEnding': '1998-12-31', 'reportedEPS': '-0.25'}, {'fiscalDateEnding': '1997-12-31', 'reportedEPS': '-0.08'}], 'quarterlyEarnings': [{'fiscalDateEnding': '2026-06-30', 'reportedDate': '2026-07-30', 'reportedEPS': '1.88', 'estimatedEPS': '1.83', 'surprise': '0.05', 'surprisePercentage': '2.7322', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2026-03-31', 'reportedDate': '2026-04-29', 'reportedEPS': '2.78', 'estimatedEPS': '1.64', 'surprise': '1.14', 'surprisePercentage': '69.5122', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2025-12-31', 'reportedDate': '2026-02-05', 'reportedEPS': '1.95', 'estimatedEPS': '1.95', 'surprise': '0', 'surprisePercentage': '0', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2025-09-30', 'reportedDate': '2025-10-30', 'reportedEPS': '1.95', 'estimatedEPS': '1.56', 'surprise': '0.39', 'surprisePercentage': '25', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2025-06-30', 'reportedDate': '2025-07-31', 'reportedEPS': '1.68', 'estimatedEPS': '1.32', 'surprise': '0.36', 'surprisePercentage': '27.2727', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2025-03-31', 'reportedDate': '2025-05-01', 'reportedEPS': '1.59', 'estimatedEPS': '1.36', 'surprise': '0.23', 'surprisePercentage': '16.9118', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2024-12-31', 'reportedDate': '2025-02-06', 'reportedEPS': '1.86', 'estimatedEPS': '1.4837', 'surprise': '0.3763', 'surprisePercentage': '25.3623', 'reportTime': 'pre-market'}, {'fiscalDateEnding': '2024-09-30', 'reportedDate': '2024-10-31', 'reportedEPS': '1.43', 'estimatedEPS': '1.14', 'surprise': '0.29', 'surprisePercentage': '25.4386', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2024-06-30', 'reportedDate': '2024-08-01', 'reportedEPS': '1.26', 'estimatedEPS': '1.02', 'surprise': '0.24', 'surprisePercentage': '23.5294', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2024-03-31', 'reportedDate': '2024-04-30', 'reportedEPS': '0.98', 'estimatedEPS': '0.82', 'surprise': '0.16', 'surprisePercentage': '19.5122', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2023-12-31', 'reportedDate': '2024-02-01', 'reportedEPS': '1', 'estimatedEPS': '0.8', 'surprise': '0.2', 'surprisePercentage': '25', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2023-09-30', 'reportedDate': '2023-10-26', 'reportedEPS': '0.94', 'estimatedEPS': '0.58', 'surprise': '0.36', 'surprisePercentage': '62.069', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2023-06-30', 'reportedDate': '2023-08-03', 'reportedEPS': '0.65', 'estimatedEPS': '0.34', 'surprise': '0.31', 'surprisePercentage': '91.1765', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2023-03-31', 'reportedDate': '2023-04-27', 'reportedEPS': '0.31', 'estimatedEPS': '0.21', 'surprise': '0.1', 'surprisePercentage': '47.619', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2022-12-31', 'reportedDate': '2023-02-02', 'reportedEPS': '0.03', 'estimatedEPS': '0.17', 'surprise': '-0.14', 'surprisePercentage': '-82.3529', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2022-09-30', 'reportedDate': '2022-10-27', 'reportedEPS': '0.28', 'estimatedEPS': '0.21', 'surprise': '0.07', 'surprisePercentage': '33.3333', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2022-06-30', 'reportedDate': '2022-07-28', 'reportedEPS': '-0.2', 'estimatedEPS': '0.12', 'surprise': '-0.32', 'surprisePercentage': '-266.6667', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2022-03-31', 'reportedDate': '2022-04-28', 'reportedEPS': '-0.38', 'estimatedEPS': '0.42', 'surprise': '-0.8', 'surprisePercentage': '-190.4762', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2021-12-31', 'reportedDate': '2022-02-03', 'reportedEPS': '1.39', 'estimatedEPS': '0.18', 'surprise': '1.21', 'surprisePercentage': '672.2222', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2021-09-30', 'reportedDate': '2021-10-28', 'reportedEPS': '0.31', 'estimatedEPS': '0.44', 'surprise': '-0.13', 'surprisePercentage': '-29.5455', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2021-06-30', 'reportedDate': '2021-07-29', 'reportedEPS': '0.76', 'estimatedEPS': '0.61', 'surprise': '0.15', 'surprisePercentage': '24.5902', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2021-03-31', 'reportedDate': '2021-04-29', 'reportedEPS': '0.79', 'estimatedEPS': '0.47', 'surprise': '0.32', 'surprisePercentage': '68.0851', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2020-12-31', 'reportedDate': '2021-02-02', 'reportedEPS': '0.7', 'estimatedEPS': '0.35', 'surprise': '0.35', 'surprisePercentage': '100', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2020-09-30', 'reportedDate': '2020-10-29', 'reportedEPS': '0.62', 'estimatedEPS': '0.38', 'surprise': '0.24', 'surprisePercentage': '63.1579', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2020-06-30', 'reportedDate': '2020-07-30', 'reportedEPS': '0.52', 'estimatedEPS': '0.08', 'surprise': '0.44', 'surprisePercentage': '550', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2020-03-31', 'reportedDate': '2020-04-30', 'reportedEPS': '0.25', 'estimatedEPS': '0.31', 'surprise': '-0.06', 'surprisePercentage': '-19.3548', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2019-12-31', 'reportedDate': '2020-01-30', 'reportedEPS': '0.32', 'estimatedEPS': '0.2', 'surprise': '0.12', 'surprisePercentage': '60', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2019-09-30', 'reportedDate': '2019-10-24', 'reportedEPS': '0.21', 'estimatedEPS': '0.22', 'surprise': '-0.01', 'surprisePercentage': '-4.5455', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2019-06-30', 'reportedDate': '2019-07-25', 'reportedEPS': '0.26', 'estimatedEPS': '0.28', 'surprise': '-0.02', 'surprisePercentage': '-7.1429', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2019-03-31', 'reportedDate': '2019-04-25', 'reportedEPS': '0.35', 'estimatedEPS': '0.23', 'surprise': '0.12', 'surprisePercentage': '52.1739', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2018-12-31', 'reportedDate': '2019-01-31', 'reportedEPS': '0.3', 'estimatedEPS': '0.28', 'surprise': '0.02', 'surprisePercentage': '7.1429', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2018-09-30', 'reportedDate': '2018-10-25', 'reportedEPS': '0.29', 'estimatedEPS': '0.15', 'surprise': '0.14', 'surprisePercentage': '93.3333', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2018-06-30', 'reportedDate': '2018-07-26', 'reportedEPS': '0.25', 'estimatedEPS': '0.13', 'surprise': '0.12', 'surprisePercentage': '92.3077', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2018-03-31', 'reportedDate': '2018-04-26', 'reportedEPS': '0.16', 'estimatedEPS': '0.06', 'surprise': '0.1', 'surprisePercentage': '166.6667', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2017-12-31', 'reportedDate': '2018-02-01', 'reportedEPS': '0.11', 'estimatedEPS': '0.09', 'surprise': '0.02', 'surprisePercentage': '22.2222', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2017-09-30', 'reportedDate': '2017-10-26', 'reportedEPS': '0.03', 'estimatedEPS': '0.03', 'surprise': '0', 'surprisePercentage': '0', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2017-06-30', 'reportedDate': '2017-07-27', 'reportedEPS': '0.02', 'estimatedEPS': '0.07', 'surprise': '-0.05', 'surprisePercentage': '-71.4286', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2017-03-31', 'reportedDate': '2017-04-27', 'reportedEPS': '0.07', 'estimatedEPS': '0.06', 'surprise': '0.01', 'surprisePercentage': '16.6667', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2016-12-31', 'reportedDate': '2017-02-02', 'reportedEPS': '0.08', 'estimatedEPS': '0.07', 'surprise': '0.01', 'surprisePercentage': '14.2857', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2016-09-30', 'reportedDate': '2016-10-27', 'reportedEPS': '0.03', 'estimatedEPS': '0.04', 'surprise': '-0.01', 'surprisePercentage': '-25', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2016-06-30', 'reportedDate': '2016-07-28', 'reportedEPS': '0.09', 'estimatedEPS': '0.05', 'surprise': '0.04', 'surprisePercentage': '80', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2016-03-31', 'reportedDate': '2016-04-28', 'reportedEPS': '0.05', 'estimatedEPS': '0.03', 'surprise': '0.02', 'surprisePercentage': '66.6667', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2015-12-31', 'reportedDate': '2016-01-28', 'reportedEPS': '0.05', 'estimatedEPS': '0.08', 'surprise': '-0.03', 'surprisePercentage': '-37.5', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2015-09-30', 'reportedDate': '2015-10-22', 'reportedEPS': '0.01', 'estimatedEPS': '-0.01', 'surprise': '0.02', 'surprisePercentage': '200', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2015-06-30', 'reportedDate': '2015-07-23', 'reportedEPS': '0.01', 'estimatedEPS': '-0.01', 'surprise': '0.02', 'surprisePercentage': '200', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2015-03-31', 'reportedDate': '2015-04-23', 'reportedEPS': '-0.01', 'estimatedEPS': '-0.01', 'surprise': '0', 'surprisePercentage': '0', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2014-12-31', 'reportedDate': '2015-01-29', 'reportedEPS': '0.02', 'estimatedEPS': '0.01', 'surprise': '0.01', 'surprisePercentage': '100', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2014-09-30', 'reportedDate': '2014-10-23', 'reportedEPS': '-0.05', 'estimatedEPS': '-0.04', 'surprise': '-0.01', 'surprisePercentage': '-25', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2014-06-30', 'reportedDate': '2014-07-24', 'reportedEPS': '-0.01', 'estimatedEPS': '-0.01', 'surprise': '0', 'surprisePercentage': '0', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2014-03-31', 'reportedDate': '2014-04-24', 'reportedEPS': '0.01', 'estimatedEPS': '0.01', 'surprise': '0', 'surprisePercentage': '0', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2013-12-31', 'reportedDate': '2014-01-30', 'reportedEPS': '0.03', 'estimatedEPS': '0.03', 'surprise': '0', 'surprisePercentage': '0', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2013-09-30', 'reportedDate': '2013-10-24', 'reportedEPS': '-0.09', 'estimatedEPS': '-0.09', 'surprise': '0', 'surprisePercentage': '0', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2013-06-30', 'reportedDate': '2013-07-25', 'reportedEPS': '-0.02', 'estimatedEPS': '0.05', 'surprise': '-0.07', 'surprisePercentage': '-140', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2013-03-31', 'reportedDate': '2013-04-25', 'reportedEPS': '0.01', 'estimatedEPS': '0.08', 'surprise': '-0.07', 'surprisePercentage': '-87.5', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2012-12-31', 'reportedDate': '2013-01-29', 'reportedEPS': '0.01', 'estimatedEPS': '0.01', 'surprise': '0', 'surprisePercentage': '0', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2012-09-30', 'reportedDate': '2012-10-25', 'reportedEPS': '-0.03', 'estimatedEPS': '-0.08', 'surprise': '0.05', 'surprisePercentage': '62.5', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2012-06-30', 'reportedDate': '2012-07-26', 'reportedEPS': '0.01', 'estimatedEPS': '0.02', 'surprise': '-0.01', 'surprisePercentage': '-50', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2012-03-31', 'reportedDate': '2012-04-26', 'reportedEPS': '0.01', 'estimatedEPS': '0.07', 'surprise': '-0.06', 'surprisePercentage': '-85.7143', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2011-12-31', 'reportedDate': '2012-01-31', 'reportedEPS': '0.02', 'estimatedEPS': '0.01', 'surprise': '0.01', 'surprisePercentage': '100', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2011-09-30', 'reportedDate': '2011-10-25', 'reportedEPS': '0.01', 'estimatedEPS': '0.01', 'surprise': '0', 'surprisePercentage': '0', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2011-06-30', 'reportedDate': '2011-07-26', 'reportedEPS': '0.02', 'estimatedEPS': '0.02', 'surprise': '0', 'surprisePercentage': '0', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2011-03-31', 'reportedDate': '2011-04-26', 'reportedEPS': '0.02', 'estimatedEPS': '0.03', 'surprise': '-0.01', 'surprisePercentage': '-33.3333', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2010-12-31', 'reportedDate': '2011-01-27', 'reportedEPS': '0.05', 'estimatedEPS': '0.04', 'surprise': '0.01', 'surprisePercentage': '25', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2010-09-30', 'reportedDate': '2010-10-21', 'reportedEPS': '0.03', 'estimatedEPS': '0.02', 'surprise': '0.01', 'surprisePercentage': '50', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2010-06-30', 'reportedDate': '2010-07-22', 'reportedEPS': '0.02', 'estimatedEPS': '0.03', 'surprise': '-0.01', 'surprisePercentage': '-33.3333', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2010-03-31', 'reportedDate': '2010-04-22', 'reportedEPS': '0.03', 'estimatedEPS': '0.03', 'surprise': '0', 'surprisePercentage': '0', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2009-12-31', 'reportedDate': '2010-01-28', 'reportedEPS': '0.04', 'estimatedEPS': '0.04', 'surprise': '0', 'surprisePercentage': '0', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2009-09-30', 'reportedDate': '2009-10-22', 'reportedEPS': '0.02', 'estimatedEPS': '0.02', 'surprise': '0', 'surprisePercentage': '0', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2009-06-30', 'reportedDate': '2009-07-23', 'reportedEPS': '0.02', 'estimatedEPS': '0.02', 'surprise': '0', 'surprisePercentage': '0', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2009-03-31', 'reportedDate': '2009-04-23', 'reportedEPS': '0.02', 'estimatedEPS': '0.02', 'surprise': '0', 'surprisePercentage': '0', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2008-12-31', 'reportedDate': '2009-01-29', 'reportedEPS': '0.03', 'estimatedEPS': '0.02', 'surprise': '0.01', 'surprisePercentage': '50', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2008-09-30', 'reportedDate': '2008-10-22', 'reportedEPS': '0.01', 'estimatedEPS': '0.01', 'surprise': '0', 'surprisePercentage': '0', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2008-06-30', 'reportedDate': '2008-07-23', 'reportedEPS': '0.02', 'estimatedEPS': '0.01', 'surprise': '0.01', 'surprisePercentage': '100', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2008-03-31', 'reportedDate': '2008-04-23', 'reportedEPS': '0.02', 'estimatedEPS': '0.02', 'surprise': '0', 'surprisePercentage': '0', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2007-12-31', 'reportedDate': '2008-01-30', 'reportedEPS': '0.02', 'estimatedEPS': '0.02', 'surprise': '0', 'surprisePercentage': '0', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2007-09-30', 'reportedDate': '2007-10-23', 'reportedEPS': '0.01', 'estimatedEPS': '0.01', 'surprise': '0', 'surprisePercentage': '0', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2007-06-30', 'reportedDate': '2007-07-24', 'reportedEPS': '0.01', 'estimatedEPS': '0.01', 'surprise': '0', 'surprisePercentage': '0', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2007-03-31', 'reportedDate': '2007-04-24', 'reportedEPS': '0.01', 'estimatedEPS': '0.01', 'surprise': '0', 'surprisePercentage': '0', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2006-12-31', 'reportedDate': '2007-02-01', 'reportedEPS': '0.01', 'estimatedEPS': '0.01', 'surprise': '0', 'surprisePercentage': '0', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2006-09-30', 'reportedDate': '2006-10-24', 'reportedEPS': '0.05', 'estimatedEPS': '0.03', 'surprise': '0.02', 'surprisePercentage': '66.6667', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2006-06-30', 'reportedDate': '2006-07-25', 'reportedEPS': '0.05', 'estimatedEPS': '0.06', 'surprise': '-0.01', 'surprisePercentage': '-16.6667', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2006-03-31', 'reportedDate': '2006-04-25', 'reportedEPS': '0.01', 'estimatedEPS': '0.01', 'surprise': '0', 'surprisePercentage': '0', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2005-12-31', 'reportedDate': '2006-02-02', 'reportedEPS': '0.01', 'estimatedEPS': '0.01', 'surprise': '0', 'surprisePercentage': '0', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2005-09-30', 'reportedDate': '2005-10-25', 'reportedEPS': '0.01', 'estimatedEPS': '0.01', 'surprise': '0', 'surprisePercentage': '0', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2005-06-30', 'reportedDate': '2005-07-26', 'reportedEPS': '0.01', 'estimatedEPS': '0.01', 'surprise': '0', 'surprisePercentage': '0', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2005-03-31', 'reportedDate': '2005-04-26', 'reportedEPS': '0.01', 'estimatedEPS': '0.01', 'surprise': '0', 'surprisePercentage': '0', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2004-12-31', 'reportedDate': '2005-02-02', 'reportedEPS': '0.02', 'estimatedEPS': '0.02', 'surprise': '0', 'surprisePercentage': '0', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2004-09-30', 'reportedDate': '2004-10-21', 'reportedEPS': '0.01', 'estimatedEPS': '0.01', 'surprise': '0', 'surprisePercentage': '0', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2004-06-30', 'reportedDate': '2004-07-22', 'reportedEPS': '0.01', 'estimatedEPS': '0.01', 'surprise': '0', 'surprisePercentage': '0', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2004-03-31', 'reportedDate': '2004-04-22', 'reportedEPS': '0.01', 'estimatedEPS': '0.01', 'surprise': '0', 'surprisePercentage': '0', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2003-12-31', 'reportedDate': '2004-01-27', 'reportedEPS': '0.01', 'estimatedEPS': '0.01', 'surprise': '0', 'surprisePercentage': '0', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2003-09-30', 'reportedDate': '2003-10-21', 'reportedEPS': '0.01', 'estimatedEPS': '0.1', 'surprise': '-0.09', 'surprisePercentage': '-90', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2003-06-30', 'reportedDate': '2003-07-22', 'reportedEPS': '0.01', 'estimatedEPS': '0.06', 'surprise': '-0.05', 'surprisePercentage': '-83.3333', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2003-03-31', 'reportedDate': '2003-04-24', 'reportedEPS': '0.01', 'estimatedEPS': '0.04', 'surprise': '-0.03', 'surprisePercentage': '-75', 'reportTime': 'post-market'}, {'fiscalDateEnding': '2002-12-31', 'reportedDate': '2003-01-23', 'reportedEPS': '0.01', 'estimatedEPS': '0.01', 'surprise': '0', 'surprisePercentage': '0', 'reportTime': 'post-marke

In [21]:
#pprint(dic_requisicao)

resultado = pd.DataFrame(dic_requisicao['quarterlyEarnings'])
display(resultado)

,fiscalDateEnding,reportedDate,reportedEPS,estimatedEPS,surprise,surprisePercentage,reportTime
0,2026-06-30,2026-07-30,1.88,1.83,0.05,2.7322,post-market
1,2026-03-31,2026-04-29,2.78,1.64,1.14,69.5122,post-market
2,2025-12-31,2026-02-05,1.95,1.95,0,0,post-market
3,2025-09-30,2025-10-30,1.95,1.56,0.39,25,post-market
4,2025-06-30,2025-07-31,1.68,1.32,0.36,27.2727,post-market
...,...,...,...,...,...,...,...
112,1998-06-30,1998-07-22,-0.07,-0.07,0,0,pre-market
113,1998-03-31,1998-04-27,-0.03,-0.04,0.01,25,pre-market
114,1997-12-31,1998-01-22,-0.03,-0.04,0.01,25,pre-market
115,1997-09-30,1997-10-27,-0.03,-0.03,0,0,pre-market
116,1997-06-30,1997-07-10,-0.02,-0.03,0.01,33.3333,pre-market